### ISSUE TITLE
Mismatch repo-name and go package name

### ISSUE THREAD

**Issue by ringods** [terra-farm/go-virtualbox#10]
Hello @VoyTechnology,

I'm trying to create a new Go module out of this repo. But the [Package Names](https://golang.org/doc/code.html#PackageNames) of `How to Write Go Code` page mentions this:

> The first statement in a Go source file must be
> `package name`
> where name is the package's default name for imports. (All files in a package must use the same name.)
> Go's convention is that the package name is the last element of the import path: the package imported as `"crypto/rot13"` should be named `rot13`.

The import path is now `github.com/terra-farm/go-virtualbox`. The last part is `go-virtualbox` and the package name is currently `virtualbox`. This is clearly not according to the above recommendation.

I see two options:
* Rename this repository from `go-virtualbox` to `virtualbox`. This breaks current users pointing to this repo as `go-virtualbox`.
* Create a subfolder `virtualbox` in the root of this repo and move all code in it. Users of this library should adapt their import statements to read `github.com/terra-farm/go-virtualbox/virtualbox`

What do you prefer? I would go for the first.

**Comment by VoyTechnology** [comment]
There is no need to change anything. While not ideal, it will actually work. Using the `go-` prefix is the standard for organisations with libraries written in multiple languages, so most developers will have no problem. Please refer to this example from https://github.com/jet/go-interstellar

https://github.com/jet/go-interstellar/blob/d647b3b61374381033ec5e117beebf807017d247/go.mod#L1-L9

As you can see, the `go.mod` file specifies the module as `go-interstellar`, but the go package name is still just `interstellar`

https://github.com/jet/go-interstellar/blob/d647b3b61374381033ec5e117beebf807017d247/client.go#L17

When using the library it is possible to just use

```
// go.mod
...
require {
    github.com/jet/go-interstellar v0.0.1
}
```

```go
// code.go

import (
    "github.com/jet/go-interstellar"
)

func main() {
  interstellar.NewClient(...)
]
```

The following works the same way, but removes the confusion
```go
// code.go

import (
    interstellar "github.com/jet/go-interstellar"
)

func main() {
  interstellar.NewClient(...)
]
```

**Comment by ringods** [comment]
So the `go` tool seems to ignore the `go-` prefix? Is this written somewhere? Or does this work by accident?

**Comment by VoyTechnology** [comment]
I think the import path just says where to import from, but the package name can be different. I just should be the same so its clearer. I believe this will still work:

```go
// the actual package provided here is bar, but from the name
// its very not clear, hence not its recommended
import "example.com/foo"

func main() {
  bar.Baz()
}
```

**Comment by ringods** [comment]
OK, given the repo is only prefixed with `go-`, I will leave it as it is. Hopefully, it keeps on working.
