### ISSUE TITLE
VBoxManage is missing from CI

### ISSUE THREAD

**Issue by VoyTechnology** [terra-farm/go-virtualbox#14]
This affects #13 and #11 from what I can see and is blocking the merge of the PRs.

**Comment by nevill** [comment]
It seems this project never had a success [build](https://travis-ci.org/terra-farm/go-virtualbox/builds) from very beginning. It requires to mock the output `VBoxManage` to make the test passed.

**Comment by VoyTechnology** [comment]
#15 Adds the ability to override the executor, meaning we can mock the output, but that still needs to be done. Right now it works like [volkswagen] and all tests just pass. I would rather not have each test add to a massive list of elements to the `vbm_test.go` file, so I would suggest in each test you can specify the output you want.

```go
func mockOutput(out string) {
  defaultExecutor = mockExecutor{out}
}
```

```go
func TestListMachines(t *testing.T) {
  testCases := map[string]struct{
    out string
    want []*Machine
    wantErr error
  }{
    "empty": {
      "",
      []*Machine{},
      nil
    },
    "single: {
      "\"Test\" {1b2de526-b913-482a-b8aa-dfef87bbb840}",
      []*Machine{&Machine{Name: "Test", UUID: "1b2de526-b913-482a-b8aa-dfef87bbb840"},
      nil,
    },
    "error": {
      "VBoxManage: error: Unknown option: --status",
      []*Machine{},
      ErrUnknownOption,
    },
  }

  for name, tc := range testCases {
    t.Run(name, func(t *testing.T) {
      mockOutput(tc.out)

      ms, err := ListMachines()
      if errors.Is(err, tc.wantErr) {
        t.Errorf("ListMachines() err = %v, want %v", err, tc.wantErr)
      }
      if diff := deep.Equal(ms, tc.want) {
        t.Errorf("ListMachines() = %v, want %v, diff: %v", err, tc.want, diff)
      }
    })
  }
}
```

[volkswagen]: https://github.com/auchenberg/volkswagen

**Comment by ringods** [comment]
#17 fixed this with a full mock setup.
